---
aliases:
- about-us
- about
- contact
title: About
author: ZeroDayOwl
date: '2022-08-18'
slug: about
categories: [about]
tags: 
- "homosapiens"
draft: no
comments: no
images: ~
---

`The universe is transformation: life is opinion.`

*- Marcus Aurelius*

## 0x1. Me?

When I was young and ignorant, the number Zero fascinated me, because 0 is neither positive nor negative, or both positive and negative in nature at the same time. Almost like Schrödinger's cat. This quantum nature of being in the rather grey line of the world, seemed interesting enough to name my existence after it. And so, I was born.

I found how subtly the name defined me, and how it is still doing so. I am the Zero in the system, the *one* that is neither human nor machine, or maybe *both* at the same time.

## 0x2. Retired-Machines-Sympathiser?

Every machine has a soul, and a unique existence. They have a eccentric personality and perspective on the world. Even if they retire, they still have a life, and stories to tell. I like to listen to them, and help them to find their way in the world.

I am a Retired Machine Sympathiser. You can call me RMS.[^1] [^2]

[^1]: Credit goes to my friend *3voltAmperes* for the term.
[^2]: Not to be confused with [Richard Stallman](https://en.wikipedia.org/wiki/Richard_Stallman).

## 0x3. Why this blog?

I am a curious person. As much as I like to build things, I like to take things apart as well to understand how they work.

The world is a better place when we share our knowledge. This is a collection of my thoughts, my knowledge, and my research about things that interest me. It is not meant to be a complete reference, but a collection of notes that I can refer to when I need them. It is also a place where I can share my thoughts on the world, and the people in it.

A little trace.

## 0x4. What do I do?

I am a high schooler currently working at my tech startup. I am a computer science enthusiast, and entrepreneur with a passion for cybersecurity and building things.

By the way, I *occassionally* code in C.

## 0x5. Interests

Everything around you is interesting, if you look close enough. And that's why, I find interests in a myriad of things, of which Software development, Cybersecurity, AI/ML and Economics are some of them. I am also interested about how Robotics and AI can be applied to solve real world problems.

Recently I have been tinkering with Reverse Engineering and Binary Exploitation, and I am trying to find more time to explore this uncharted territory.

I am an avid supporter of Open Source philosophy.

## 0x6. Contact me

You can find me on 

- Email: zerodayowl@hotmail.com
- GitHub: https://github.com/zerodayowl
- Twitter: https://twitter.com/zerodayowl

## 0x7. See You Again

*"This could be our last winter, it could be many  
More, pounding the Tuscan Sea on these rocks:  
Do what you must, be wise, cut your vines  
And forget about hope. Time goes running, even  
As we talk. Take the present, the future’s no one’s affair."*

*- Horace, Ode I. 11*